name: SimpleMessages
description: Show players information from text files
version: ${project.version}
author: James Richardson (grandwazir)
website: ${project.url}
main: name.richardson.james.bukkit.simplemessages.SimpleMessages